### ISSUE TITLE
Issues using package

### ISSUE THREAD

**Issue by xdg6227** [EdouardCourty/user-instagram#15]
I was trying to use this package for my bot and whenever I run the command, in my console it says: 
```js
(node:979) UnhandeledPromiseRejectionWarning: TypeError: Cannot read property 'user' of undefined
     at /home/runner/MLlama-Bot/node_modules/user-instagram/src/scrape.js:23:37
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
...

**Comment by EdouardCourty** [comment]
Can you send me the code snippet using the function causing the error please ?
