### ISSUE TITLE
Crash when user not found.

### ISSUE THREAD

**Issue by LWJerri** [EdouardCourty/user-instagram#18]
When I try a search user without an account my app crash with this error:
```js
var error = new Error(message);
              ^

Error: Request failed with status code 404
    at createError (C:\Users\Andrey\Desktop\jobs\testdiscord\node_modules\user-instagram\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Andrey\Desktop\jobs\testdiscord\node_modules\user-instagram\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Andrey\Desktop\jobs\testdiscord\node_modules\user-instagram\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (node:events:341:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {..SOME ERROR..}```

**Comment by EdouardCourty** [comment]
Hello, can you copy and paste the code snippets using the module ?

**Comment by LWJerri** [comment]
> Hello, can you copy and paste the code snippets using the module ?

I clone this repository, change the username to random, and start code.

**Comment by EdouardCourty** [comment]
I'll push a fix asap. Sorry for the inconvenience !
I will tag you whenever you can update.

**Comment by LWJerri** [comment]
> I'll push a fix asap. Sorry for the inconvenience !
> I will tag you whenever you can update.

Okay, thanks!

**Comment by EdouardCourty** [comment]
Hello, I'm sorry I did not fix it already, got a load of work to do. I'm trying to push it before this evening !

**Comment by EdouardCourty** [comment]
You can update to 2.1.9. In case the user or post does not exist, a catchable error will be thrown.
