### ISSUE TITLE
UnableToFetchPostDataError: An error occured while fetching post

### ISSUE THREAD

**Issue by 89z** [EdouardCourty/user-instagram#35]
Using this program:

~~~js
const userInstagram = require("user-instagram");

userInstagram.getPostData('CT-cnxGhvvO')
  .then(console.log)
  .catch(console.error);
~~~

I get this result:

~~~
UnableToFetchPostDataError: An error occured while fetching post data for
shortcode CT-cnxGhvvO. Maybe this post does not exist ?
    at Function.fromShortcode (D:\Desktop\node_modules\user-instagram\src\Exceptions\UnableToFetchPostDataError.js:7:12)
    at D:\Desktop\node_modules\user-instagram\src\scrape.js:156:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
~~~

The post does exist, so something else is going on.

**Comment by DonkeyKongJr** [comment]
I guess Instagram has enforced some new restrictions. I get a similar error when trying to access a user with the package.

```
Access to XMLHttpRequest at 'https://www.instagram.com/acp_gruppe/?__a=1' from origin 'https://<whatever>.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

and then 

```
Error: An error occured while fetching data for user acp_gruppe. Maybe this user does not exist.
```

but surely the user exists.^

Probably it's related to this: https://stackoverflow.com/questions/66336314/new-cors-policy-for-instagram-public-api

**Comment by 89z** [comment]
@skodem I ended up writing my own package. It works for the example above. However its in a different language, so I dont know if it will be useful to you:

https://github.com/89z/mech

**Comment by EdouardCourty** [comment]
I released a new version of the module fixing this issue. Use 3.0.0 !
Have a good day :)
