### ISSUE TITLE
Unkown error

### ISSUE THREAD

**Issue by iWedmak** [EdouardCourty/user-instagram#46]
InstagramGenericError: Unkown error, please submit an issue on GitHub with the following error message: Request failed with status code 400
17:30:45 1|stars  |     at /var/www/node_modules/user-instagram/src/Instagram/Infrastructure/InstagramRepository.js:382:23
17:30:45 1|stars  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)

i do get this on auth

**Comment by EdouardCourty** [comment]
Hello there, it seems like something changed on Instagram's side.
I'll update asap.

**Comment by ikverenc** [comment]
any news?

**Comment by ongkay** [comment]
any news?
